tests(pathlib): Fix test failing because of old pathlib
Test was failing with the following error:
`AttributeError: 'WindowsPath' object has no attribute 'expanduser'`.
This is probably caused by an old version of `pathlib` being installed
during tests, which does not implement the `expanduser` method.